#
# vim: ts=8 noet sw=8:
#


TOP := 			.
include 		config.mk

BINDIR      		:= $(PREFIX)/bin
MAN1DIR     		:= $(PREFIX)/man/man1

OCAMLC_FLAGS            := -g -dtypes 
OCAMLOPT_FLAGS          := -p -dtypes 
OCAMLOPT_FLAGS          := -p -dtypes 
OCAMLOPT_FLAGS          :=    -dtypes 


# ------------------------------------------------------------------ 
# high-level targets
# ------------------------------------------------------------------ 

.PHONY: 	all clean install

all: 		ocamlburg.$(BINEXT) runtime.$(BINEXT) examples.$(BINEXT)

clean:
		rm -f *.cmo *.cmx *.o *.cmi *.ml *.mli *.mll *.mly
		rm -f *.byte *.opt 
		rm -f *.output *.annot
		rm -f sample.mlb
		rm -f *.aux *.inc *.tex *.log *.out *.pdf

clobber: 	clean
		rm -f config.mk DEPEND


install: 	ocamlburg.$(BINEXT) dirs
		cp ocamlburg.$(BINEXT) 	$(BINDIR)/ocamlburg
		cp ocamlburgfix   	$(BINDIR)
		cp ocamlburgfix.1 	$(MAN1DIR)
		cp ocamlburg.1    	$(MAN1DIR)
		@echo "====================================================="
		@echo "The following files are required by the code"
		@echo "generated by OCamlburg. Please copy them manually"
		@echo "to a location (like `$(OCAMLC) -where`) where"
		@echo "the OCaml compiler can find them. The list of file:"
		@echo camlburg.*
		@echo "====================================================="
		

dirs: 		
		test -d $(BINDIR)  || mkdir -p $(BINDIR)
		test -d $(MAN1DIR) || mkdir -p $(MAN1DIR)

config.mk: 	configure
		echo "Have you run ./configure? Please do."
		exit 1


# ------------------------------------------------------------------ 
# rules
# ------------------------------------------------------------------ 

%.cmi:		%.mli
		$(OCAMLC) $(OCAMLC_FLAGS) -c $<

%.cmo:		%.ml
		$(OCAMLC) $(OCAMLC_FLAGS) -c $<

%.o %.cmx:	%.ml
		$(OCAMLOPT) $(OCAMLO_FLAGS) -c $<

%.ml:		%.mll
		$(OCAMLLEX) $<

%.mli		\
%.ml		\
%.output:	%.mly
		$(OCAMLYACC) -v $<

%.ml:		%.nw
		$(NOTANGLE) -L'# %L "%F"%N' -R$@ $< > $@

%.mli:		%.nw
		$(NOTANGLE) -L'# %L "%F"%N' -R$@ $< > $@
		
# ------------------------------------------------------------------ 
# special rules to resolve ambiguities
# ------------------------------------------------------------------ 

parse.mly:	parse.nw
		$(NOTANGLE) -R$@ $< > $@

parse.ml:	parse.mly

lex.mll:	lex.nw
		$(NOTANGLE) -R$@ $< > $@
		
lex.ml:		lex.mll		

# ------------------------------------------------------------------ 
# files
# ------------------------------------------------------------------ 

ML =		pretty.ml 	\
		srcmap.ml	\
		code.ml		\
		mangler.ml	\
		spec.ml		\
		parseerror.ml	\
		parse.ml	\
		lex.ml		\
		norm.ml		\
		burg.ml		\
                noguardscheck.ml\
		main.ml		\
		
MLI =		pretty.mli 	\
		srcmap.mli	\
		burg.mli	\
		code.mli	\
		main.mli	\
		mangler.mli	\
		norm.mli	\
		parse.mli	\
		parseerror.mli	\
		spec.mli	\

NW := 		$(wildcard *.nw)

SCAN =		$(ML) $(MLI) \
		camlburg.ml camlburg.mli\
		sampleclient.ml\


CMO =		$(addsuffix .cmo,$(basename $(ML))) 
CMX =		$(addsuffix .cmx,$(basename $(ML))) 

TEX :=      	$(patsubst %.nw, %.tex, $(NW))
INC :=      	$(patsubst %.nw, %.inc, $(NW))
PDF :=      	$(patsubst %.nw, %.pdf, $(NW))

# ------------------------------------------------------------------ 
# binaries
# ------------------------------------------------------------------ 

ocamlburg.byte:	$(CMO)
		$(OCAMLC) $(OCAMLC_FALGS) -o $@ $(CMO)

ocamlburg.opt:	$(CMX)
		$(OCAMLOPT) $(OCAMLO_FLAGS) -o $@ $(CMX)

# ------------------------------------------------------------------ 
# runtime code, examples
# ------------------------------------------------------------------ 

sample.mlb:	sample.nw
		$(NOTANGLE) -L'# %L "%F"%N' -R$@ $< > $@

sampleclient.ml:    sample.nw
		$(NOTANGLE) -L'# %L "%F"%N' -R$@ $< > $@
		
iburg.ml:	iburg.mlb ocamlburg.$(BINEXT) runtime.$(BINEXT)
		./ocamlburg.$(BINEXT) iburg.mlb | ./ocamlburgfix $@

sample.ml:	sample.mlb ocamlburg.$(BINEXT) runtime.$(BINEXT)
		./ocamlburg.$(BINEXT) sample.mlb | ./ocamlburgfix $@

runtime.byte:	camlburg.ml camlburg.cmo camlburg.cmi camlburg.mli
runtime.opt:	camlburg.ml camlburg.cmx camlburg.cmi camlburg.mli camlburg.o

examples.byte:	iburg.cmo sample.cmo sampleclient.cmo
examples.opt:	iburg.cmx sample.cmx sampleclient.cmx

# -- documentation

RERUN =     Rerun (LaTeX|to get cross-references right)

pdf:	    $(PDF)

%.pdf:	%.tex 
	    $(PDFLATEX) $<
	    if egrep -s '$(RERUN)' $*.log ;then $(PDFLATEX) $<; fi
	    if egrep -s '$(RERUN)' $*.log ;then $(PDFLATEX) $<; fi

%.inc:      %.nw
	    $(NOWEAVE) -delay $< > $@

%.tex:	%.inc
	    echo "    \documentclass[11pt]{article}	"  > $@
	    echo "    \usepackage{hyperref}		" >> $@
	    echo "    \usepackage{noweb}		" >> $@
	    echo "    \usepackage{xspace}		" >> $@
	    echo "    \noweboptions{breakcode}		" >> $@
	    echo "    \begin{document}			" >> $@
	    echo "    \def\ocaml{OCaml\xspace}		" >> $@	
	    echo "    \let\module\texttt		" >> $@	
	    echo "    \input{$<}			" >> $@
	    echo "    \end{document}			" >> $@


# ------------------------------------------------------------------ 
# dependencies
# ------------------------------------------------------------------ 

DEPEND:     	$(SCAN)
		$(OCAMLDEP) $(SCAN) > DEPEND   

include	DEPEND

# ------------------------------------------------------------------ 


